<a href="https://colab.research.google.com/github/G0nkly/pytorch_sandbox/blob/main/gpts/nanoGPT/AK_GPT_DIY_RECAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Load the data
# Encoding / Decodingz
# Train/Test Split | get_batch function

In [2]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2026-09-30 05:56:02--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.01s   

2026-09-30 05:56:02 (111 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [3]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [4]:
with open("./input.txt") as file:
  text = file.read()

In [5]:
vocab = sorted(set([c for c in text.strip()]))
stoi = {v: k  for k,v in enumerate(vocab)}
itos = {k: v  for k,v in enumerate(vocab)}
encode = lambda chars: [stoi[char] for char in chars]
decode = lambda indices: "".join(itos[index] for index in indices)

In [29]:
###################
# HYPERPARAMETERS #
###################
vocab_size = len(vocab)
block_size = 8
batch_size = 8
embed_dim = 32
n_heads = 4
n_blocks = 4
dropout = 0.2
learning_rate = 1e-03
eval_iter = 200
n_epochs = 1000
train_test_split = 0.8
device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
data = torch.tensor(encode(text))

In [8]:
data[:10]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47])

In [9]:
train_index = int(train_test_split * len(data))
train = data[:train_index]
test = data[train_index:]
indices = torch.randint(0, len(train) - block_size, (batch_size,))
indices

tensor([ 56281, 696590,  62837, 385491,  15677, 690624, 283189, 371577])

In [10]:
indices = torch.randint(0, len(train) - block_size,(1,8))
indices = indices.squeeze(0).tolist()
x = []
y = []
for index in indices:
  x.append(torch.stack([train[index + i] for i in range(0, block_size)]))
  y.append(torch.stack([train[index + i + 1] for i in range(0, block_size)]))

X = torch.stack(x)
Y = torch.stack(y)

X, Y


(tensor([[43, 39, 58, 46,  1, 53, 44,  1],
         [57, 43,  6,  0, 35, 46, 47, 41],
         [39, 45, 43,  1, 47, 57,  1, 57],
         [61, 47, 57, 46,  6,  1, 61, 46],
         [ 1, 58, 46, 47, 52, 43,  1, 59],
         [53, 61,  1, 57, 61, 39, 63, 57],
         [53,  1, 40, 43, 58, 47, 42, 11],
         [42,  1, 51, 43, 11,  0, 35, 46]]),
 tensor([[39, 58, 46,  1, 53, 44,  1, 54],
         [43,  6,  0, 35, 46, 47, 41, 46],
         [45, 43,  1, 47, 57,  1, 57, 53],
         [47, 57, 46,  6,  1, 61, 46, 47],
         [58, 46, 47, 52, 43,  1, 59, 52],
         [61,  1, 57, 61, 39, 63, 57,  1],
         [ 1, 40, 43, 58, 47, 42, 11,  0],
         [ 1, 51, 43, 11,  0, 35, 46, 53]]))

In [11]:
def get_batch(split = "train"):
  data = train if split == "train" else test
  indices = torch.randint(0, len(train) - block_size, (batch_size,))

  x = []
  y = []
  for index in indices:
    x.append(torch.stack([train[index + i] for i in range(0, block_size)]))
    y.append(torch.stack([train[index + i + 1] for i in range(0, block_size)]))

  X = torch.stack(x)
  Y = torch.stack(y)

  return X, Y

In [30]:
@torch.no_grad()
def evaluate_model(model):
  model.eval()
  losses = torch.zeros(eval_iter)
  for i in range(eval_iter):
    x_train, y_train = get_batch("test")
    logits, _ = model(x_train)
    B, T, C = logits.shape
    logits = logits.view(B*T, C)
    y_train = y_train.view(B * T)
    loss = F.cross_entropy(logits, y_train)
    losses[i] = loss
  model.train()
  return losses.mean()

In [ ]:
# Training
def train_model(model, n_epochs=n_epochs):
  model.train()
  optimizer = torch.optim.Adam(params=model.parameters(), lr=learning_rate)
  losses = torch.zeros(n_epochs)
  for epoch in range(n_epochs):
    xb, targets = get_batch()
    logits, loss = model(xb, targets)
    losses[epoch] = loss.item()
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if epoch % eval_iter == 0 or epoch == n_epochs - 1:
      eval_loss = evaluate_model(model)
      print(f"Epoch: {epoch}, Train Loss: {loss.item()}, Eval Loss: {eval_loss}")


In [15]:
################
# BUILD MODELS #
################

In [16]:
class BigramModel(nn.Module):

  def __init__(self):
    super().__init__()
    self.embd = nn.Embedding(vocab_size, vocab_size)
  def forward(self, inputs, targets=None):
    x = self.embd(inputs)
    if targets is not None:
      B, T, C = x.shape
      targets = targets.view(B*T)
      loss = F.cross_entropy(x.view(B*T,C), targets)
      return x, loss
    return x, None

  def generate(self, start_token, n_tokens):
    for _ in range(n_tokens):
      input = start_token[-block_size:]                     # (B, T, C)
      logits, loss = self(input)                            # (B, T, C)
      logits = logits[:, -1, :]                             # (B, 1, C)
      probs = nn.functional.softmax(logits, dim=-1)         # (B, 1, C)
      idx = torch.multinomial(probs, num_samples=1)         # (B, 1)
      start_token = torch.cat((input, idx), dim=-1)         # (B, T+1)

    return start_token


In [17]:
emb = nn.Embedding(vocab_size, vocab_size)
preds = emb(torch.tensor(0).unsqueeze(0))
probs = nn.functional.softmax(preds, -1)
idx = torch.multinomial(probs, 1)
preds.shape, probs.shape

(torch.Size([1, 65]), torch.Size([1, 65]))

In [18]:
model = BigramModel()
start_token = torch.tensor(encode(" "))
token_ids = model.generate(start_token.unsqueeze(0), 100).squeeze().tolist()
decode(token_ids)

" Vdej,:DWPDe-!N;b;BvizJIfNVkcTrNs::DlVC!w$ilVmG?VjfWGQQ DHDAR.qSms\nMlLmZx'Xch&O LOX\nzWhrdatK,YWG Abcd"

In [19]:
class AttentionHead(nn.Module):

  def __init__(self):
    super().__init__()
    self.head_size = embed_dim // n_heads
    self.query = nn.Linear(embed_dim, self.head_size)
    self.key = nn.Linear(embed_dim, self.head_size)
    self.value = nn.Linear(embed_dim, self.head_size)
    self.dropout = nn.Dropout(dropout)
    self.register_buffer("tril", torch.tril(torch.ones(block_size, block_size)))

  def forward(self, x):
    B, T, C = x.shape
    query = self.query(x)
    key = self.key(x)
    value = self.value(x)
    x = query @ torch.transpose(key, -1, 1)
    x = (x / (self.head_size**-0.5))
    mask = torch.masked_fill(x, self.tril[:block_size, :block_size] == 0 ,float("-inf"))
    mask = torch.nn.functional.softmax(mask, dim=-1)
    mask = self.dropout(mask)
    x = mask @ value
    return x

In [20]:
class FeedForward(nn.Module):

  def __init__(self):
    super().__init__()
    self.ff = nn.Sequential(
        nn.Linear(embed_dim, 4 * embed_dim),
        nn.ReLU(),
        nn.Dropout(dropout),
        nn.Linear(4 * embed_dim, embed_dim)
    )

  def forward(self, x):
    x = self.ff(x)
    return x

In [21]:
class MultiHeadAttention(nn.Module):

  def __init__(self):
    super().__init__()
    self.layer_norm1 = nn.LayerNorm(embed_dim)
    self.layer_norm2 = nn.LayerNorm(embed_dim)
    self.attention_heads = nn.ModuleList([AttentionHead() for _ in range(n_heads)])
    self.ff = FeedForward()
    self.dropout = nn.Dropout(dropout)

  def forward(self, x):
    x = x + self.layer_norm1(self.dropout(x))
    x = torch.cat([head(x) for head in self.attention_heads], dim=-1)
    x = x + self.layer_norm2(self.dropout(x))
    x = self.ff(x)
    return x

In [22]:
class TheGodamnTransformer(nn.Module):

  def __init__(self):
    super().__init__()
    self.embed = nn.Embedding(vocab_size, embed_dim)
    self.positional_encoding = nn.Embedding(block_size, embed_dim)
    self.attention_blocks = nn.Sequential(*[MultiHeadAttention() for _ in range(n_blocks)])
    self.projection = nn.Linear(embed_dim, vocab_size)

  def forward(self, x):
    x = self.embed(x) # B, T, C
    x = x + self.positional_encoding(torch.arange(0, block_size, device=device))
    x = self.attention_blocks(x)
    x = self.projection(x)
    return x

In [23]:
# Check the model
transformer = TheGodamnTransformer()
input = torch.tensor([0]).unsqueeze(dim=0)
output = transformer(input)
output.shape

torch.Size([1, 8, 65])

In [24]:
# Testbench
mask = torch.tril(torch.ones(8,8))
mask = torch.masked_fill(mask, mask[:block_size, :block_size] == 0 ,float("-inf"))
torch.nn.functional.softmax(mask, dim=-1)


tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [ ]:
model = BigramModel()

In [48]:
train_model(model=model, n_epochs=2000)

Epoch: 0, Train Loss: 2.5333240032196045, Eval Loss: 2.468715190887451
Epoch: 200, Train Loss: 2.540712833404541, Eval Loss: 2.474003791809082
Epoch: 400, Train Loss: 2.4643757343292236, Eval Loss: 2.465975046157837
Epoch: 600, Train Loss: 2.805729389190674, Eval Loss: 2.5047552585601807
Epoch: 800, Train Loss: 2.667133092880249, Eval Loss: 2.445852279663086
Epoch: 1000, Train Loss: 2.320497751235962, Eval Loss: 2.4588029384613037
Epoch: 1200, Train Loss: 2.3112714290618896, Eval Loss: 2.4494593143463135
Epoch: 1400, Train Loss: 2.886751174926758, Eval Loss: 2.4733760356903076
Epoch: 1600, Train Loss: 2.417555332183838, Eval Loss: 2.450387477874756
Epoch: 1800, Train Loss: 2.685748338699341, Eval Loss: 2.4604804515838623
Epoch: 1999, Train Loss: 2.4615352153778076, Eval Loss: 2.460512638092041


In [49]:
start_token = torch.tensor(encode(" "))
token_ids = model.generate(start_token.unsqueeze(0), 100).squeeze().tolist()
decode(token_ids)

" me rt aspiveang kend, stho' a ormy, ndoutealimersha bat's r wastosas, ales m, th fo l, rathe havenoo"